### ISSUE TITLE
Migration to restify beta, errors in cors

### ISSUE THREAD

**Issue by royibernthal** [Tabcorp/restify-cors-middleware#22] opened 2017-01-11 18:19 UTC
I'm migrating from the stable restify version to the beta version, and I'm experiencing errors when trying to migrate from restify.CORS to this restify-cors-middleware module.

My node app works well, but when I try to require the restify-cors-middleware module I get errors (without any further use of this module, only requiring it at the moment):

> project_path\node_modules\restify-cors-middleware\src\preflight.js:15
> var DEFAULT_ALLOW_HEADERS = restify.CORS.ALLOW_HEADERS;
>                                         ^
> 
> TypeError: Cannot read property 'ALLOW_HEADERS' of undefined
>     at Object.<anonymous> (project_path\node_modules\restify-cors-middleware\
> src\preflight.js:15:41)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (project_path\node_modules\restify-cors-middleware\
> src\index.js:2:18)
>     at Module._compile (module.js:571:32)

**Comment by royibernthal** [comment] 2017-01-14 21:43
When I looked closely at the npm list of installed modules I noticed it's not even supposed to work for restify beta? (beta is version 5 and above)

> npm ERR! peer dep missing: restify@2.6.x - 4.3.x, required by restify-cors-middleware@0.0.8

If that is the case, is there another way for me to use CORS in the beta?

**Comment by royibernthal** [comment] 2017-01-22 23:22
Is there no solution for it at all in the beta?

**Comment by simonepri** [comment] 2017-01-23 11:18
There are a lot of differences from 4.x to 5.x so I think that another branch should be opened to adapt this middleware to restify 5.x. I think you are welcome to made a PR for this.

**Comment by royibernthal** [comment] 2017-01-23 18:17
I have no idea how to do it myself. Is there a way to ask this repo's contributors if they can do this?

**Comment by rprieto** [comment] 2017-01-24 00:55
Hi, sorry I'm just seeing this. I'll have a look at what's needed to support Restify 5 and let you know. I'll also start talking to the Restify team to understand how we can make the CORS interface more stable.

**Comment by royibernthal** [comment] 2017-01-25 23:36
Hi, thanks, I appreciate it. Any rough estimation how long before we have 5.x support?

**Comment by MenilV** [comment] 2017-04-12 16:28
Any news on this. Beta build of restify is up since Dec, 2016.

**Comment by retrohacker** [comment] 2017-05-03 01:11
Hey @royibernthal,

@retrohacker here from the restify org. This is definitely on us, we broke a lot of the assumptions this module made with regards to the way we handle CORS requests. We have an open PR on our plugins repo and I'll look into what we can do to reconcile this new work with what is here in this repo :heart:

**Comment by retrohacker** [comment] 2017-06-22 23:31
@royibernthal this should now work with #27 if you want to give it a try :smile:

**Comment by royibernthal** [comment] 2017-06-22 23:34
I'm no longer using restify, but thank you nonetheless for solving it :)

**Comment by retrohacker** [comment] 2017-06-27 17:52
@rprieto I think this issue can be closed ^_^

**Comment by PhilHannent** [comment] 2017-06-28 10:47
@rprieto @retrohacker  

I can confirm that the current npm install fails with the current npm install restify (v5). Installing resify-cors-middleware via the github repository fixes this issue (because of the #27 fix).

A release to the npm repository would be great.

**Comment by simonepri** [comment] 2017-06-28 11:40
@retrohacker I think the `package.json` should be updated.
Do you think is reasonable to bump the version of this package to `5.0.0` in order to keep a seamless versioning with the `restify` project???

**Comment by rprieto** [comment] 2017-06-28 12:40
Thanks for confirming it all works now! I'll publish a version tomorrow morning.

@retrohacker are there any guidelines for plugin versions? I was thinking even `v1.0.0` would be a good start, now that this plugin is adds official CORS support. And because it breaks the cyclic dependency with Restify, hopefully will be compatible with all future versions.

**Comment by retrohacker** [comment] 2017-06-28 19:12
@simonepri @rprieto:

We have been talking a lot about this recently. Currently, restify doesn't have an explicit contract that it maintains with our own plugins. The current "contract" has grown organically, and isn't really stable. The root cause of this is that most of the plugins are [living inside the restify codebase](https://github.com/restify/node-restify/tree/5.x/lib/plugins). This loose contract was the main driving factor for [the recent PR](https://github.com/restify/node-restify/pull/1346) bringing the plugins back in.

While trying to keep major releases in lockstep (All `v5` releases of restify-cors-middleware being compatible with all `v5` versions of restify) sounds appealing at the surface, it introduces some complexities for plugin maintainers and how they manage breaking changes. Under this model, if you keep true to semver, you won't be able to release any breaking changes for this repo until restify cuts another major release. Likewise, you will be forced to cut a new major version whenever we release irrespective of whether or not you have breaking changes. It creates a lot of unnecessary work for maintainers.

I'd like to make our plugin story much better in the future, and I'm hoping the CORS repo living outside the restify organization will be the proverbial "fire under our butts" forcing us to make it so :wink:

For now, I think the best path forward is:

1. Plugins maintain their own semver releases (`v1.0.0` like you suggested sounds great!)
2. The restify org creates a list of all known userland plugins in our documentation
3. The restify org communicates breaking changes to plugin maintainers via the repos linked to in the documentation

What are your thoughts @rprieto?

cc:// @yunong @rajatkumar @DonutEspresso

**Comment by retrohacker** [comment] 2017-10-31 18:27
Closing as the original issue is solved.

**Closed by retrohacker** 2017-10-31 18:27 UTC
